---
name: static-checks

on:
  pull_request:
    branches:
      - master
      - main

concurrency:
  group: pr-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  static-checks:
    name: Static Checks Pull Request
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest", "macOS-latest"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'

      - name: Build
        run: go build -v ./...
        working-directory: cli

      - name: Test
        run: go test -v ./...
        working-directory: cli

      - name: Vet
        run: go vet ./...
        working-directory: cli
...
