---
name: static-checks

on:
  push:
    branches:
      - master
      - main
    tags:
      - v*
  pull_request:
    branches:
      - master
      - main

concurrency:
  group: pr-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macOS-latest"]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'

      - name: Build
        run: go build -v ./...
        working-directory: cli

      - name: Test
        run: go test -v ./...
        working-directory: cli

  static-checks:
    name: Static Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Vet
        run: go vet ./...
        working-directory: cli

      - name: Build
        run: go build ./...
        working-directory: cli

      - uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.3"
          install-go: false
          working-directory: cli

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: cli
...
